"""alignment revenue info

Revision ID: 2d4080f0ea52
Revises: c68a09d2c595
Create Date: 2024-10-07 18:31:07.413749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '2d4080f0ea52'
down_revision: Union[str, None] = 'c68a09d2c595'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

alignment_enum = postgresql.ENUM('strongly_aligned', 'aligned', 'misaligned', 'strongly_misaligned', name='alignment')



def upgrade() -> None:
    alignment_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('revenue', sa.Float(), nullable=True))
    op.add_column('nodes', sa.Column('alignment', alignment_enum, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'alignment')
    op.drop_column('nodes', 'revenue')

    alignment_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
